BetterCms.Demo.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using BetterCms.Demo.Web.Models;

using BetterCms.Module.Api;
using BetterCms.Module.Api.Infrastructure;
using BetterCms.Module.Api.Infrastructure.Enums;
using BetterCms.Module.Api.Operations.Blog.BlogPosts;
using BetterCms.Module.Api.Operations.Root.Categories;

namespace BetterCms.Demo.Web.Controllers
{
    public class BlogController : Controller
    {
        public virtual ActionResult Index(Guid? categoryId, string tagName)
        {
            IList<BlogItem> posts;
            
            using (var api = ApiFactory.Create())
            {
                var request = new GetBlogPostsModel { Take = 10, IncludeTags = true };

                var orFilter = new DataFilter(FilterConnector.Or);
                orFilter.Add("ExpirationDate", null);
                orFilter.Add("ExpirationDate", DateTime.Today, FilterOperation.GreaterOrEqual);

                request.Order.By.Add(new OrderItem("ActivationDate", OrderDirection.Desc));
                request.Order.By.Add(new OrderItem("Id"));
                request.Filter.Add("ActivationDate", DateTime.Today, FilterOperation.LessOrEqual);
                request.Filter.Inner.Add(orFilter);
                if (categoryId.HasValue)
                {
                    request.Filter.Add("CategoryId", categoryId.Value);
                }

                if (!string.IsNullOrEmpty(tagName))
                {
                    request.FilterByTags.Add(tagName);
                }

                var pages = api.Blog.BlogPosts.Get(new GetBlogPostsRequest { Data = request });
                
                posts = pages.Data.Items.Select(
                        x => new BlogItem
                        {
                            IntroText = x.IntroText, 
                            PublishedOn = x.ActivationDate, 
                            Title = x.Title, 
                            Url = x.BlogPostUrl,
                            Author = x.AuthorName,
                            Tags = x.Tags
                        }).ToList();
            }
            
            return View(posts);
        }

        public virtual ActionResult Last()
        {
            BlogItem post = null;

            using (var api = ApiFactory.Create())
            {
                var requestLatestNewsModel = new GetBlogPostsModel { Take = 1, IncludeTags = true };

                var orFilter = new DataFilter(FilterConnector.Or);

                orFilter.Add("ExpirationDate", null);
                orFilter.Add("ExpirationDate", DateTime.Today, FilterOperation.GreaterOrEqual);

                requestLatestNewsModel.Order.By.Add(new OrderItem("ActivationDate", OrderDirection.Desc));
                requestLatestNewsModel.Order.By.Add(new OrderItem("Id"));
                requestLatestNewsModel.Filter.Add("ActivationDate", DateTime.Today, FilterOperation.LessOrEqual);

                requestLatestNewsModel.Filter.Inner.Add(orFilter);

                var request = new GetBlogPostsRequest { Data = requestLatestNewsModel };

                var pages = api.Blog.BlogPosts.Get(request);

                post = pages.Data.Items.Select(
                        x => new BlogItem
                        {
                            IntroText = x.IntroText,
                            PublishedOn = x.ActivationDate,
                            Title = x.Title,
                            Url = x.BlogPostUrl,
                            Author = x.AuthorName,
                            Tags = x.Tags
                        }).SingleOrDefault();
            }

            return View(post);            
        }

        public virtual ActionResult GetCategories()
        {
            IList<CategoryItem> categories;

            using (var api = ApiFactory.Create())
            {
                var request = new GetCategoriesRequest();
                request.Data.Order.By.Add(new OrderItem("Name"));

                var pages = api.Root.Categories.Get(request);

                categories = pages.Data.Items.Select(
                        x => new CategoryItem
                        {
                            Id = x.Id,
                            Name = x.Name
                        }).ToList();
            }

            return View(categories);
        }

        public virtual ActionResult Feed()
        {
            IList<BlogItem> posts;

            using (var api = ApiFactory.Create())
            {
                var request = new GetBlogPostsModel { Take = 10, IncludeTags = true };

                var orFilter = new DataFilter(FilterConnector.Or);
                orFilter.Add("ExpirationDate", null);
                orFilter.Add("ExpirationDate", DateTime.Today, FilterOperation.GreaterOrEqual);

                request.Order.By.Add(new OrderItem("ActivationDate", OrderDirection.Desc));
                request.Order.By.Add(new OrderItem("Id"));
                request.Filter.Add("ActivationDate", DateTime.Today, FilterOperation.LessOrEqual);

                var pages = api.Blog.BlogPosts.Get(new GetBlogPostsRequest { Data = request });

                posts = pages.Data.Items.Select(
                        x => new BlogItem
                        {
                            IntroText = x.IntroText,
                            PublishedOn = x.ActivationDate,
                            Title = x.Title,
                            Url = x.BlogPostUrl,
                            Author = x.AuthorName,
                            ImageUrl = x.MainImageUrl,
                            Tags = x.Tags
                        }).ToList();
            }

            return View(posts);
        }
    }
}

BetterCms.Demo.Web/Controllers/ContactController.cs
using System;
using System.Net.Mail;
using System.Web.Mvc;

using BetterCms.Demo.Web.Helpers;
using BetterCms.Demo.Web.Models;

namespace BetterCms.Demo.Web.Controllers
{
    public class ContactController : Controller
    {
        [HttpPost]
        public virtual ActionResult ContactForm(ContactFormViewModel viewModel)
        {
            bool success;
            if (ModelState.IsValid)
            {
                using (var message = new MailMessage())
                {
                    message.From = new MailAddress("contact@fataco.com");
                    message.ReplyToList.Add(new MailAddress(viewModel.Email));
                    message.To.Add(new MailAddress(viewModel.EmailTo));
                    message.Subject = string.Format("[Fataco.com] Message from {0}", viewModel.Name);
                    message.IsBodyHtml = true;
                    message.Body = EmailHelper.FormatMessage(viewModel);

                    try
                    {
                        SmtpClient client = new SmtpClient();
                        client.Send(message);
                        success = true;
                    }
                    catch (Exception)
                    {
                        success = false;
                    }
                }
            }
            else
            {
                success = false;
            }
            System.Globalization.CultureInfo c = (System.Globalization.CultureInfo)Session["Culture"];
            if (c.Name == "en")
            {

                return new JsonResult
                {
                    Data = new
                    {
                        success = success,
                        message = success ? "Your message successfully send." : "Sorry there has been an error while sending your message, please try again later."
                    }
                };
            }
            else {

                return new JsonResult
                {
                    Data = new
                    {
                        success = success,
                        message = success ? "Yêu cầu của bạn đã được gởi tới FATACO" : "Xin lổi, Yêu cầu của bạn chưa được gởi đi, vui lòng thử lại lần nữa."
                    }
                };
            }
           
        }
    }
}

BetterCms.Demo.Web/Views/Widgets/BlogFeedWidget.cshtml
@{ Html.RenderAction("Feed", "Blog", new { area = string.Empty }); }

BetterCms.Demo.Web/Views/Widgets/CategoriesMenuWdiget.cshtml
@{ Html.RenderAction("GetCategories", "Blog", new { area = string.Empty }); }

BetterCms.Demo.Web/Views/Widgets/ContactFormWidget.cshtml
@using BetterCms.Demo.Web.Helpers
@model BetterCms.Demo.Web.Models.ContactFormViewModel

@{ Model.EmailTo = OptionsHelper.GetValue(Model.Options, "EmailToAddress");
   System.Globalization.CultureInfo c = (System.Globalization.CultureInfo)Session["Culture"];
}



<div class="contactWarp">

@using (Html.BeginForm("ContactForm", "Contact", FormMethod.Post, new { @class = "autobind" }))
{
    if (c != null && c.Name == "en")
    {
    <div class="heading3">Send request</div>
    }
    else
    {               
    <div class="heading3">Gửi yêu cầu</div>
    }
   

    <div class="field-holder">
        <div>
            @if (c != null && c.Name == "en")
            {
                <span>Name</span>
            }
            else
            {               
                <span>Họ Tên</span>
            }

        </div>
        @Html.TextBoxFor(m => m.Name, new { @class = "text-field", style = "width:100%;height:20px;" })
        @Html.ValidationMessageFor(m => m.Name)
    </div>

    <div class="field-holder">
        <div>
            @Html.LabelFor(m => m.Email)
        </div>
        @Html.TextBoxFor(m => m.Email, new { @class = "text-field", style = "width:100%;height:20px;" })
        @Html.ValidationMessageFor(m => m.Email)
    </div>

    <div class="field-holder">
        <div>
            @if (c != null && c.Name == "en")
            {
                <span>Message</span>
            }
            else
            {               
                <span>Nội dung</span>
            }
        </div>
        @Html.TextAreaFor(m => m.Message, new { @class = "text-area", style = "width:100%;height: 80px;" })
        @Html.ValidationMessageFor(m => m.Message)
    </div>
    
    @Html.HiddenFor(m => m.EmailTo)
@*<a class="btn-primary" data-url="/contacts/submit-form">Send</a>*@
   <div style="text-align:center;"> 
            @if (c != null && c.Name == "en")
            {
<a id="contactSubmit" class="button1" data-url="/contacts/submit-form" >Send</a>
    @*<a data-url="/contacts/submit-form" class="btn-primary">Send</a>*@
            }
            else
            {               
<a id="contactSubmit" class="button1" data-url="/contacts/submit-form">Gửi yêu cầu</a>
                <img style="display:none;" id="contactLoading" src="/Content/Fataco/js/colorbox/images/loading.gif" />
    @*<a data-url="/contacts/submit-form" class="btn-primary">Send</a>*@
            }
</div>

}
</div>
<div class="contactMessage" style="display:none;color:#247FC1;margin-top:20px;border:solid 2px #404040;padding:10px;border-radius:10px;">

</div>
<script type="text/javascript">
    $(document).ready(function () {

        $('#contactSubmit').click(function () {
            var $form = $('form.autobind'),
               $link = $('#contactSubmit'),
               url = $link.data('url');
            if ($form.valid()) {
                $('#contactLoading').show();
                $('#contactSubmit').hide();
                var data = $form.serialize(); 
                $.post(url, data)
                    .done(function (result) {
                        $('#contactLoading').hide();
                        $('#contactSubmit').show();
                        $('.contactMessage').show();
                        $('.contactMessage').text(result.message);
                        //if (result.success) {
                            
                        //    alert(result.message);
                            
                        //} else {
                        //    alert(result.message);
                        //}
                    }).fail(function () {
                        onError();
                    }).always(function () {
                    });
            }
            return false;
        });
    });
</script>

BetterCms.Demo.Web/Views/Widgets/GoogleMapWidget.cshtml
@using BetterCms.Demo.Web.Helpers
@{
    var center = OptionsHelper.GetValue(Model.Options, "Center");
    var address1 = OptionsHelper.GetValue(Model.Options, "Address1");
    var address2 = OptionsHelper.GetValue(Model.Options, "Address2");
    var address3 = OptionsHelper.GetValue(Model.Options, "Address3");

    var maker1 = OptionsHelper.GetValue(Model.Options, "Maker1");
    var maker2 = OptionsHelper.GetValue(Model.Options, "Maker2");
    var maker3 = OptionsHelper.GetValue(Model.Options, "Maker3");
    
    
   
    
}
<style>
    #mapCanvas1404904741
    {
        width: 620px;
        height: 650px; margin-left:10px;
    }
</style>

<div id="mapCanvas1404904741"></div>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
    var directionsDisplay;
    var directionsService = new google.maps.DirectionsService();
    var geocoder1404904741;
    var map1404904741;
    var marker1404904741;
    var info_window = new google.maps.InfoWindow({
        content: 'loading'
    });
    var bounds = new google.maps.LatLngBounds();
    map1404904741 = new google.maps.Map(
         document.getElementById('mapCanvas1404904741'),
         {
             scrollwheel: false,
             zoom: 14,
             mapTypeId: google.maps.MapTypeId.ROADMAP
         }
    );
    @if (center != null)
    {
            @Html.Raw("map1404904741.setCenter(new google.maps.LatLng(" + center + "));")
    }
        
    @if (maker1 != null)
    {
            @Html.Raw("  marker1404904741 = new google.maps.Marker({")
            @Html.Raw("            position: new google.maps.LatLng(" + maker1 + "),")
            @Html.Raw("            icon: \"\",")
            @Html.Raw("            title: 'Point', map: map1404904741")
            @Html.Raw("             , html: \"<div style='max-height:200px; max-width:450px;'>" + address1 + "</div>\"")
            @Html.Raw("        });")
            @Html.Raw("    google.maps.event.addListener(marker1404904741, 'click', function () {")
            @Html.Raw("        info_window.setContent(this.html);")
            @Html.Raw("        info_window.open(map1404904741, this);")
            @Html.Raw("    });")

            @Html.Raw("bounds.extend(new google.maps.LatLng(" + maker1 + "));");
    }
         
    @if (maker2 != null)
    {
            @Html.Raw("  marker1404904741 = new google.maps.Marker({")
            @Html.Raw("            position: new google.maps.LatLng(" + maker2 + "),")
            @Html.Raw("            icon: \"\",")
            @Html.Raw("            title: 'Point', map: map1404904741")
            @Html.Raw("             , html: \"<div style='max-height:200px; max-width:450px;'>" + address2 + "</div>\"")
            @Html.Raw("        });")
            @Html.Raw("    google.maps.event.addListener(marker1404904741, 'click', function () {")
            @Html.Raw("        info_window.setContent(this.html);")
            @Html.Raw("        info_window.open(map1404904741, this);")
            @Html.Raw("    });")

            @Html.Raw("bounds.extend(new google.maps.LatLng(" + maker2 + "));");
    }
         
          @if (maker1 != null)
          {
            @Html.Raw("  marker1404904741 = new google.maps.Marker({")
            @Html.Raw("            position: new google.maps.LatLng(" + maker3 + "),")
            @Html.Raw("            icon: \"\",")
            @Html.Raw("            title: 'Point', map: map1404904741")
            @Html.Raw("             , html: \"<div style='max-height:200px; max-width:450px;'>" + address3 + "</div>\"")
            @Html.Raw("        });")
            @Html.Raw("    google.maps.event.addListener(marker1404904741, 'click', function () {")
            @Html.Raw("        info_window.setContent(this.html);")
            @Html.Raw("        info_window.open(map1404904741, this);")
            @Html.Raw("    });")

            @Html.Raw("bounds.extend(new google.maps.LatLng(" + maker3 + "));");
          }

    //marker1404904741 = new google.maps.Marker({
    //    position: new google.maps.LatLng(10.7670591, 106.650145),
    //    icon: "",
    //    title: 'Point', map: map1404904741
    //     , html: "<div style='max-height:200px; max-width:450px;'>VĂN PHÒNG</div>"
    //});
    //google.maps.event.addListener(marker1404904741, 'click', function () {
    //    info_window.setContent(this.html);
    //    info_window.open(map1404904741, this);
    //});

    //bounds.extend(new google.maps.LatLng(10.7670591, 106.650145));
    //marker1404904741 = new google.maps.Marker({
    //    position: new google.maps.LatLng(10.7649142, 106.6503221),
    //    icon: "",
    //    title: 'Point', map: map1404904741
    //     , html: "<div style='max-height:200px; max-width:450px;'>CHI NHÁNH </div>"
    //});
    //google.maps.event.addListener(marker1404904741, 'click', function () {
    //    info_window.setContent(this.html);
    //    info_window.open(map1404904741, this);
    //});

    //bounds.extend(new google.maps.LatLng(10.7649142, 106.6503221));
    //marker1404904741 = new google.maps.Marker({
    //    position: new google.maps.LatLng(10.8310667, 106.6051751),
    //    icon: "",
    //    title: 'Point', map: map1404904741
    //     , html: "<div style='max-height:200px; max-width:450px;'>XƯỞNG SẢN XUẤT </div>"
    //});
    //google.maps.event.addListener(marker1404904741, 'click', function () {
    //    info_window.setContent(this.html);
    //    info_window.open(map1404904741, this);
    //});

    //bounds.extend(new google.maps.LatLng(10.8310667, 106.6051751));
    map1404904741.fitBounds(bounds);
    map1404904741.panToBounds(bounds);
    $("#mapCanvas1404904741").mousedown(function (e) { e.stopPropagation(); e.stopImmediatePropagation(); });
</script>

BetterCms.Demo.Web/Views/Widgets/LastBlogPostWidget.cshtml
@{ Html.RenderAction("Last", "Blog", new { area = string.Empty }); }

BetterCms.Demo.Web/Views/Widgets/LatestBlogPostsWdiget.cshtml
@{ Html.RenderAction("Index", "Blog", new { area = string.Empty }); }

BetterCms.Demo.Web/Views/Widgets/RedirectWidget.cshtml
@using BetterCms.Demo.Web.Helpers
@{
    var Url = OptionsHelper.GetValue(Model.Options, "Url");
    if (Url != null)
    { 
        Response.Redirect(Url);  
    }
}

BetterCms.Demo.Web/Views/Widgets/SocialWidget.cshtml
@using BetterCms.Demo.Web.Helpers
@using BetterCms.Module.Root.ViewModels.Cms
@model RenderWidgetViewModel

@{
    var useSideBoxOption = OptionsHelper.GetValue(Model.Options, "useSideBox");
    var useSideBox = !string.IsNullOrWhiteSpace(useSideBoxOption) && Convert.ToBoolean(useSideBoxOption);
}

@if (useSideBox)
{
    @:<div class="side-box">
}

<h2>@Html.TitleForSocial()</h2>

<div class="social-logo clearfix">
    @Html.LinkForSocial("facebookShouldRender", "facebookUrl", "facebookTitle", "facebookCssClass")
    @Html.LinkForSocial("twitterShouldRender", "twitterUrl", "twitterTitle", "twitterCssClass")
    @Html.LinkForSocial("linkedinShouldRender", "linkedinUrl", "linkedinTitle", "linkedinCssClass")
</div>
<div class="social-logo clearfix">
    @Html.LinkForSocial("skypeShouldRender", "skypeUrl", "skypeTitle", "skypeCssClass")
    @Html.LinkForSocial("youtubeShouldRender", "youtubeUrl", "youtubeTitle", "youtubeCssClass")
    @Html.LinkForSocial("flickrShouldRender", "flickrUrl", "flickrTitle", "flickrCssClass")
</div>

@if (useSideBox)
{
    @:</div>
}

BetterCms.Demo.Web/Views/Widgets/SubMenuWidget.cshtml
@using BetterCms.Demo.Web.Helpers
@{
    var parentUrl = OptionsHelper.GetValue(Model.Options, "parentUrl");
    if (parentUrl != null)
    {
        Html.RenderAction("SubMenu", "Sitemap", new { area = string.Empty, parentUrl = parentUrl });        
    }
}