BetterCMS.Module.Store/Controllers/WidgetController.cs
using BetterCms.Module.Root.Mvc;
using BetterCMS.Module.Store.Commands.Widget;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using BetterCMS.Module.Store.ViewModels;
using System.Web.Configuration;
using System.Text;
using BetterCMS.Module.Store.Helpers;

namespace BetterCMS.Module.Store.Controllers
{
    public class WidgetController : CmsControllerBase
    {
        private void GetRecursiveCategories(string categoryId, ref List<string> categories)
        {
            categories.Add(categoryId);
            var subCategories = GetCommand<GetSubCategoriesCommand>().ExecuteCommand(categoryId);
            if (subCategories.Count > 0)
            {
                foreach (var item in subCategories)
                {
                    GetRecursiveCategories(item.Id.ToString().ShortGuid(), ref categories);
                }
            }
        }

        private List<ProductViewModel> GetProductList(List<string> categories)
        {
            List<ProductViewModel> allProducts = new List<ProductViewModel>();
            foreach (var item in categories)
            {
                var listProduct = GetCommand<GetProductListByCategoryIdCommand>().ExecuteCommand(item);
                if (listProduct.Count > 0)
                {
                    foreach (var product in listProduct)
                    {
                        allProducts.Add(product);
                    }
                }
            }
            return allProducts;
        }
        public ActionResult ProductList(string id, int? page, string detailUrl)
        {
            ViewBag.DetailUrl = detailUrl;
            if (!string.IsNullOrEmpty(id))
            {
                var category = GetCommand<GetCategoryCommand>().ExecuteCommand(id);
                //var listProduct = GetCommand<GetProductListByCategoryIdCommand>().ExecuteCommand(id);
                List<string> categories = new List<string>();
                GetRecursiveCategories(id, ref categories);
                var listProduct = GetProductList(categories);
                var pageNumber = page ?? 1;
                var pageSize = int.Parse(WebConfigurationManager.AppSettings["PageSize"].ToString());
                var pagedList = listProduct.ToPagedList(pageNumber, pageSize);
                bool showPager = false;
                if (listProduct.Count > pageSize)
                {
                    showPager = true;
                }
                ViewBag.ShowPager = showPager;
                ViewBag.Category = category;
                ViewBag.AllProduct = false;
                return View(pagedList);
            }
            else
            {
                var rootCategories = GetCommand<GetSubCategoriesCommand>().ExecuteCommand("00000000");
                if (rootCategories.Count > 2)
                {
                    var firstCategory = rootCategories.ElementAt(0);
                    var secondCategory = rootCategories.ElementAt(1);
                    var thirdCategory = rootCategories.ElementAt(2);
                    List<string> firstCategories = new List<string>();
                    GetRecursiveCategories(firstCategory.Id.ToString().ShortGuid(), ref firstCategories);
                    List<string> secondCategories = new List<string>();
                    GetRecursiveCategories(secondCategory.Id.ToString().ShortGuid(), ref secondCategories);
                    List<string> thirdCategories = new List<string>();
                    GetRecursiveCategories(thirdCategory.Id.ToString().ShortGuid(), ref thirdCategories);
                    var firstProducts = GetProductList(firstCategories);
                    var secondProducts = GetProductList(secondCategories);
                    var thirdProducts = GetProductList(thirdCategories);

                    ViewBag.FirstCategory = firstCategory;
                    ViewBag.SecondCategory = secondCategory;
                    ViewBag.ThirdCategory = thirdCategory;

                    var rand = new Random();

                    ViewBag.FirstProducts = firstProducts.OrderBy(t => rand.Next()).Take(4).ToList();
                    ViewBag.SecondProducts = secondProducts.OrderBy(t => rand.Next()).Take(4).ToList();
                    ViewBag.ThirdProducts = thirdProducts.OrderBy(t => rand.Next()).Take(4).ToList();
                }
                ViewBag.AllProduct = true;
                return View();
            }
        }

        public ActionResult FeaturedProduct(string detailUrl)
        {
            var listProduct = GetCommand<GetFeaturedProductCommand>().ExecuteCommand(string.Empty);
            ViewBag.DetailUrl = detailUrl;
            return View(listProduct);
        }

        public ActionResult SearchResult(string query, int? page, string detailUrl)
        {
            var listProduct = GetCommand<GetProductListByQueryCommand>().ExecuteCommand(query);
            var pageNumber = page ?? 1;
            var pageSize = int.Parse(WebConfigurationManager.AppSettings["PageSize"].ToString());
            var pagedList = listProduct.ToPagedList(pageNumber, pageSize);
            bool showPager = false;
            if (listProduct.Count > pageSize)
            {
                showPager = true;
            }
            ViewBag.ShowPager = showPager;
            ViewBag.DetailUrl = detailUrl;
            return View(pagedList);
        }

        private List<ProductViewModel> GetRealtedProducts(string[] shortIDs)
        {
            List<ProductViewModel> relatedProducts = new List<ProductViewModel>();
            foreach (var shortID in shortIDs)
            {
                var product = GetCommand<GetProductByShortIDCommand>().ExecuteCommand(shortID);
                if (product != null)
                {
                    relatedProducts.Add(product);
                }
            }
            return relatedProducts;
        }

        public ActionResult ProductDetail(string id)
        {
            var model = GetCommand<GetProductByIdCommand>().ExecuteCommand(id);
            var category = GetCommand<GetCategoryCommand>().ExecuteCommand(model.CategoryId.ToString());
            ViewBag.Category = category;
            if (model != null && !string.IsNullOrWhiteSpace(model.Size))
            {
                string[] arr = model.Size.Split(new string[] { Environment.NewLine }, StringSplitOptions.None);
                if (arr.Length > 0)
                {
                    var relatedProducts = GetRealtedProducts(arr);
                    if (relatedProducts.Count > 0)
                    {
                        ViewBag.RelatedProducts = relatedProducts;
                    }
                }
            }
            return View(model);
        }

        public ActionResult CategoryList(string productUrl)
        {
            var list = GetCommand<GetCategoryListCommand>().ExecuteCommand(Guid.Empty);
            string id = "00000000";
            if (Request.QueryString["id"] != null)
            {
                id = Request.QueryString["id"];
            }
            
            StringBuilder sb = new StringBuilder();
            var root = list.Where(t => t.ParentId == Guid.Empty).ToList();
            sb.AppendLine("<div id=\"VMENU709487940\" class=\"VMENU\">");
            if (root.Count > 0)
            {
                sb.AppendLine("<ul class=\"VMENU_0 VMENU_0_709487940 reset\">");
                foreach (var item in root)
                {
                    string name = Utility.CurrentLanguageCode == "en" ? item.Name_en : item.Name;
                    string active_class = "";
                    string active_class_a = "";
                    if (item.Id.ToString().Contains(id))
                    {
                        active_class = "s";
                        active_class_a = "a_s";
                    }
                    var level1 = list.Where(t => t.ParentId == item.Id).OrderBy(t => t.SortOrder).ToList();
                    string url = "#";
                    //if (!string.IsNullOrWhiteSpace(productUrl) && level1.Count == 0)
                    {
                        url = productUrl + "?t=" + name.GenerateSlug() + "&id=" + item.Id.ToString().ShortGuid();
                    }
                    sb.AppendFormat("<li><a class=\""+active_class_a+"\" href=\"{0}\"><span class=\"{1}\">{2}</span></a>", url, active_class, name);
                    if (level1.Count > 0)
                    {
                        sb.AppendLine("<ul class=\"VMENU_1 VMENU_1_709487940 reset\">");
                        foreach (var item1 in level1)
                        {
                            string name1 = Utility.CurrentLanguageCode == "en" ? item1.Name_en : item1.Name;
                            string active_class1 = "";
                            string active_class1_a = "";
                            if (item1.Id.ToString().Contains(id))
                            {
                                active_class1 = "s ";
                                active_class1_a = "a_s ";
                            }
                            var level2 = list.Where(t => t.ParentId == item1.Id).OrderBy(t => t.SortOrder).ToList();
                            string url1 = "#";
                            if (!string.IsNullOrWhiteSpace(productUrl) && level2.Count == 0)
                            {
                                url1 = productUrl + "?t=" + name1.GenerateSlug() + "&id=" + item1.Id.ToString().ShortGuid();
                            }
                            sb.AppendFormat("<li><a class=\"" + active_class1_a + "" + item1.Id.ToString().ShortGuid() + "\" href=\"{0}\"><span class=\"{1}\">{2}</span></a>", url1, active_class1, name1);
                            if (level2.Count > 0)
                            {

BetterCMS.Module.Store/Views/Widget/CategoryList.cshtml
@using BetterCMS.Module.Store.ViewModels;
@using BetterCMS.Module.Store.Helpers;
@model List<CategoryViewModel>

@Html.Raw(ViewBag.MenuHtml)

BetterCMS.Module.Store/Views/Widget/CategoryListWidget.cshtml
@using BetterCMS.Module.Store.Helpers

@{
    var productUrl = OptionsHelper.GetValue(Model.Options, "ProductUrl");
    Html.RenderAction("CategoryList", "Widget", new { area = "bcms-store", productUrl = productUrl != null ? productUrl : ""});
}

BetterCMS.Module.Store/Views/Widget/FeaturedProduct.cshtml
@using BetterCMS.Module.Store.ViewModels;
@using BetterCMS.Module.Store.Helpers;

@model List<ProductViewModel>

@{
    string baseDetailUrl = ViewBag.DetailUrl;
    string headerText = "Sản phẩm nổi bật";
    if (Utility.CurrentLanguageCode == "en")
    {
        headerText = "Featured products";
    }
}


@if (Model.Count > 0)
{
    <section>
        <div class="heading2">@headerText</div>

        <div class="jcarousel-wrapper">
            <div class="jcarousel">
                <ul>
                    @foreach (var item in Model)
                    {
                        string detailUrl = "#";
                        if (!string.IsNullOrWhiteSpace(baseDetailUrl))
                        {
                            detailUrl = baseDetailUrl + "?t=" + Utility.GenerateSlug(item.Code) + "&id=" + item.Id.ToString().ShortGuid();
                        }
                        <li>
                            <a href="@detailUrl"><img src="@(item.Image != null ? item.Image.ImageUrl + "?w=180&h=180&scale=canvas" : "/content/fataco/images/no-image.jpg?w=180&h=180&scale=canvas")" alt=""></a>
                        </li>
                    }
                </ul>
            </div>
            <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
            <a href="#" class="jcarousel-control-next">&rsaquo;</a>

            @*<p class="jcarousel-pagination"></p>*@
        </div>
    </section>
}

<script type="text/javascript">
    $(function () {
        $('.jcarousel').jcarousel({
            // Configuration goes here
        });
    });
</script>

BetterCMS.Module.Store/Views/Widget/FeaturedProductWidget.cshtml
@using BetterCMS.Module.Store.Helpers

@{
    var detailUrl = OptionsHelper.GetValue(Model.Options, "DetailUrl");
    Html.RenderAction("FeaturedProduct", "Widget", new { area = "bcms-store", detailUrl = detailUrl != null ? detailUrl : "" });
}

BetterCMS.Module.Store/Views/Widget/ProductDetail.cshtml
@using BetterCMS.Module.Store.ViewModels;
@using BetterCMS.Module.Store.Helpers;

@model ProductViewModel
<style type="text/css">
    .jcarousel .m-product {
        width:160px !important;
    }
    .jcarousel-control-prev, .jcarousel-control-next {
        top: 30%;
    }
</style>
@{
    string categoryName = "";
    CategoryViewModel category = (CategoryViewModel)ViewBag.Category;
    string codeLabel = "Mã";
    string sizeLabel = "Cỡ";
    string colorLabel = "Màu";
    string infoText = "Thông tin chi tiết";
    string relatedText = "Sản phẩm liên quan";
    string description = Model.Description;
    if (Utility.CurrentLanguageCode == "en")
    {
        codeLabel = "Code";
        sizeLabel = "Size";
        colorLabel = "Color";
        infoText = "Detail information";
        relatedText = "Related products";
        if (!string.IsNullOrWhiteSpace(Model.Description_en))
        {
            description = Model.Description_en;
        }
    }
    if (category != null)
    {
        categoryName = category.Name;
        if (Utility.CurrentLanguageCode == "en")
        {
            categoryName = category.Name_en;
        }
    }
    string tempid = category.Id.ToString().ShortGuid();
    string tempParentid = category.ParentId.ToString().ShortGuid();
    ViewBag.DetailUrl = HttpContext.Current.Request.Url.AbsolutePath;
}
@if (!string.IsNullOrWhiteSpace(categoryName))
{
    <div class="heading3">@categoryName > @Model.Code</div>    
}
else
{
    <div class="heading3">@Model.Code</div>    
}
<br />
<div>
    <div class="product-image">
        <img src="@(Model.Image != null ? Model.Image.ImageUrl + "?width=700" : "/content/fataco/images/no-image.jpg?width=700")" />
    </div>

    <div>
        <div class="heading2">@infoText</div>
        <div class="m-product-name"><strong>@codeLabel: </strong>@Model.Code</div>
        @*@if (!string.IsNullOrWhiteSpace(Model.Size))
        {
            <table cellpadding="0" cellspacing="2">
                <tbody>
                    <tr>
                        <td><strong>@sizeLabel:</strong></td>
                        <td align="left">@Html.Raw(Model.Size.Replace(Environment.NewLine, "<br/>"))</td>
                    </tr>
                </tbody>
            </table>
        }*@
        @if (!string.IsNullOrWhiteSpace(Model.Color))
        { 
            <div class="m-product-desc">
                <strong style="float: left;">@colorLabel: </strong>
                @{
                    string[] arrColor = Model.Color.Split(';');
                    foreach (string color in arrColor)
                    {
                        if (!string.IsNullOrWhiteSpace(color))
                        {
                            <span style="width: 15px; height: 15px;border: 1px solid gray; margin-left: 3px; float: left; background: @color"></span>
                        }
                    }
                }
                <br>
            </div>
        }
        <div class="product-detail">
            @Html.Raw(description)
        </div>
        <br /><br />
        @if (ViewBag.RelatedProducts != null)
        {
            <div class="heading2">@relatedText</div>
            <div class="jcarousel-wrapper" style="box-shadow:none;">
                <div class="jcarousel">
                    <ul>
                        @foreach (ProductViewModel item in ViewBag.RelatedProducts)
                        {
                            { Html.RenderPartial("~/Areas/bcms-store/Views/Widget/Partial/_DisplayProduct.cshtml", item); }

                        }
                    </ul>

                </div>
                <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
                <a href="#" class="jcarousel-control-next">&rsaquo;</a>
            </div>
        }
        
    </div>
</div>

<script type="text/javascript">
    var cateID = '@tempid';
    var parentID = '@tempParentid';
    $(function () {
        $('.jcarousel').jcarousel({
            items: '.m-product',
            width: '150px'
        });
        var temp2 = 3;
      
        if (parent != '') {
            $('.' + parentID).addClass('a_s');
            $('.' + parentID).children('span').addClass('s');
        }
       
        $('.' + cateID).addClass('a_s');
        $('.' + cateID).children('span').addClass('s');
        $('.a_s').parent('li').parent('ul').each(function () {
            $(this).show();
            $(this).siblings('a').parent('li').parent('ul').show();
        });
    });
</script>

BetterCMS.Module.Store/Views/Widget/ProductDetailWidget.cshtml
@{ Html.RenderAction("ProductDetail", "Widget", new { area = "bcms-store" }); }

BetterCMS.Module.Store/Views/Widget/ProductList.cshtml
@using PagedList;
@using PagedList.Mvc;
@using BetterCMS.Module.Store.ViewModels;
@using BetterCMS.Module.Store.Helpers;

@model IPagedList<ProductViewModel>
<style type="text/css">
    .heading3 a {
        color: #6D276F;
    }
</style>
@if (ViewBag.AllProduct == false)
{
    string categoryName = "Sản phẩm";
    if (Utility.CurrentLanguageCode == "en")
    {
        categoryName = "Products";
    }
    CategoryViewModel category = (CategoryViewModel)ViewBag.Category;
    if (category != null)
    {
        categoryName = category.Name;
        if (Utility.CurrentLanguageCode == "en")
        {
            categoryName = category.Name_en;
        }
    }
    
    <link rel="stylesheet" href="/file/bcms-store/content/styles/pagedlist.css" />
    <div class="heading3">@categoryName</div>
    <div>
    @foreach (ProductViewModel item in Model)
    {
        {Html.RenderPartial("~/Areas/bcms-store/Views/Widget/Partial/_DisplayProduct.cshtml", item);}
    }
    </div>
    <div style="clear:both;"></div>
    if (ViewBag.ShowPager)
    {
        @Html.PagedListPager((IPagedList)Model, page => Utility.AppendQueryString(new List<KeyValuePair<String, String>> { new KeyValuePair<string, string>("page", page.ToString()) }))    
    }
}
else
{
    var viewAllText = "Xem tất cả";
    CategoryViewModel firstCategory = ViewBag.FirstCategory;
    CategoryViewModel secondCategory = ViewBag.SecondCategory;
    CategoryViewModel thirdCategory = ViewBag.ThirdCategory;
    string FirstCategoryTitle = firstCategory.Name;
    string SecondCategoryTitle = secondCategory.Name;
    string ThirdCategoryTitle = thirdCategory.Name;
   
    if (Utility.CurrentLanguageCode == "en")
    {
        viewAllText = "View all";
        FirstCategoryTitle = firstCategory.Name_en;
        SecondCategoryTitle = secondCategory.Name_en;
        ThirdCategoryTitle = thirdCategory.Name_en;

    }
    string firstProductUrl = "?t=" + FirstCategoryTitle.GenerateSlug() + "&id=" + firstCategory.Id.ToString().ShortGuid();
    string secondProductUrl = "?t=" + SecondCategoryTitle.GenerateSlug() + "&id=" + secondCategory.Id.ToString().ShortGuid();
    string thirdProductUrl = "?t=" + ThirdCategoryTitle.GenerateSlug() + "&id=" + thirdCategory.Id.ToString().ShortGuid();
    
    <div class="heading3"><a href="@firstProductUrl">@FirstCategoryTitle</a></div>
    <div>
        @foreach (ProductViewModel item in ViewBag.FirstProducts)
        {
            {Html.RenderPartial("~/Areas/bcms-store/Views/Widget/Partial/_DisplayProduct.cshtml", item);}
        }
    </div>
    <div style="clear:both;"></div>
    <div style="text-align:right;"><a style="font-weight: bold; color: #6d276f;" href="@firstProductUrl">@viewAllText >></a></div>
    
    <div class="heading3"><a href="@secondProductUrl">@SecondCategoryTitle</a></div>
    <div>
        @foreach (ProductViewModel item in ViewBag.SecondProducts)
        {
            {Html.RenderPartial("~/Areas/bcms-store/Views/Widget/Partial/_DisplayProduct.cshtml", item);}
        }
    </div>
    <div style="clear:both;"></div>
    <div style="text-align:right;"><a style="font-weight: bold; color: #6d276f;" href="@secondProductUrl">@viewAllText >></a></div>
    
    <div class="heading3"><a href="@thirdProductUrl">@ThirdCategoryTitle</a></div>
    <div>
        @foreach (ProductViewModel item in ViewBag.ThirdProducts)
        {
            { Html.RenderPartial("~/Areas/bcms-store/Views/Widget/Partial/_DisplayProduct.cshtml", item); }
        }
    </div>
    <div style="clear:both;"></div>
    <div style="text-align:right;"><a style="font-weight: bold; color: #6d276f;" href="@thirdProductUrl">@viewAllText >></a></div>
    
    
    
}

BetterCMS.Module.Store/Views/Widget/ProductListWidget.cshtml
@using BetterCMS.Module.Store.Helpers

@{
    var detailUrl = OptionsHelper.GetValue(Model.Options, "DetailUrl");
    Html.RenderAction("ProductList", "Widget", new { area = "bcms-store", detailUrl = detailUrl != null ? detailUrl : "" });
}

BetterCMS.Module.Store/Views/Widget/SearchResult.cshtml
@using PagedList;
@using PagedList.Mvc;
@using BetterCMS.Module.Store.ViewModels;
@using BetterCMS.Module.Store.Helpers;

@model IPagedList<ProductViewModel>

<link rel="stylesheet" href="/file/bcms-store/content/styles/pagedlist.css" />
@{
    string headerText = "Sản phẩm";
    string notFoundMsg = "Không tìm thấy sản phẩm nào.";
}

<div class="heading3">@headerText</div>
<div>
    @if (Model.Count > 0)
    {
        foreach (ProductViewModel item in Model)
    {
            {Html.RenderPartial("~/Areas/bcms-store/Views/Widget/Partial/_DisplayProduct.cshtml", item);}
        
    }
    }
    else
    {
        <i>@notFoundMsg</i>
    }
</div>

@if (ViewBag.ShowPager)
{
    @Html.PagedListPager((IPagedList)Model, page => Utility.AppendQueryString(new List<KeyValuePair<String, String>> { new KeyValuePair<string, string>("page", page.ToString()) }))
}

<div style="clear:both;"></div>

BetterCMS.Module.Store/Views/Widget/SearchResultWidget.cshtml
@using BetterCMS.Module.Store.Helpers

@{
    var detailUrl = OptionsHelper.GetValue(Model.Options, "DetailUrl");
    Html.RenderAction("SearchResult", "Widget", new { area = "bcms-store", detailUrl = detailUrl != null ? detailUrl : "" });
}