BetterCms.Demo.Web/Controllers/SitemapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using BetterCms.Demo.Web.Models;

using BetterCms.Module.Api;
using BetterCms.Module.Api.Infrastructure;
using BetterCms.Module.Api.Infrastructure.Enums;
using BetterCms.Module.Api.Operations.Pages.Pages.Page.Exists;
using BetterCms.Module.Api.Operations.Pages.Sitemap;
using BetterCms.Module.Api.Operations.Pages.Sitemap.Nodes;
using BetterCms.Module.Api.Operations.Pages.Sitemap.Tree;
using BetterCms.Module.Api.Operations.Pages.Pages.Page.Translations;
using System.Globalization;
using System.Web;
using BetterCms.Demo.Web.Helpers;


namespace BetterCms.Demo.Web.Controllers
{
    public class SiteMapController : Controller
    {
        private static Guid defaultSitemapId = new Guid("17ABFEE9-5AE6-470C-92E1-C2905036574B");

        public virtual ActionResult Index()
        {
            var menuItems = new List<MenuItemViewModel>();

            using (var api = ApiFactory.Create())
            {
                var sitemapId = GetSitemapId(api);
                if (sitemapId.HasValue)
                {
                    var request = new GetSitemapTreeRequest { SitemapId = sitemapId.Value, Data = new GetSitemapTreeModel { LanguageId = LanguageHelper.CurrentLanguageId } };

                    var response = api.Pages.Sitemap.Tree.Get(request);

                    if (response.Data.Count > 0)
                    {
                        menuItems = response.Data.Select(mi => new MenuItemViewModel { Caption = mi.Title, Url = mi.Url }).ToList();
                    }
                }
            }

            return View(menuItems);
        }

        public ActionResult TopMenu()
        {
            var menuItems = new List<MenuItemViewModel>();

            using (var api = ApiFactory.Create())
            {
                var sitemapId = GetSitemapId(api);
                if (sitemapId.HasValue)
                {
                    var request = new GetSitemapTreeRequest { SitemapId = sitemapId.Value, Data = new GetSitemapTreeModel { LanguageId = LanguageHelper.CurrentLanguageId } };

                    var response = api.Pages.Sitemap.Tree.Get(request);

                    if (response.Data.Count > 0)
                    {
                        menuItems = response.Data.Select(mi => new MenuItemViewModel { Caption = mi.Title, Url = mi.Url }).ToList();
                    }
                }
            }

            return View(menuItems);
        }


        public ActionResult FooterMenu()
        {
            var menuItems = new List<MenuItemViewModel>();

            using (var api = ApiFactory.Create())
            {
                var sitemapId = GetSitemapId(api);
                if (sitemapId.HasValue)
                {
                    var request = new GetSitemapTreeRequest { SitemapId = sitemapId.Value, Data = new GetSitemapTreeModel { LanguageId = LanguageHelper.CurrentLanguageId } };

                    var response = api.Pages.Sitemap.Tree.Get(request);
                    System.Text.StringBuilder sb = new System.Text.StringBuilder();
                    if (response.Data.Count > 0)
                    {
                        foreach (var item in response.Data)
                        {
                            if (item.ChildrenNodes.Count > 0)
                            {
                                sb.Append("<div class=\"col\">");
                                sb.Append("<h2>" + item.Title + "</h2>");
                                sb.Append("<ul>");
                                foreach (var item1 in item.ChildrenNodes)
                                {
                                    sb.Append("<li><a href=\"" + item1.Url + "\">" + item1.Title + "</a></li>");
                                }

                                sb.Append("<ul>");
                                sb.Append("</div>");

                            }
                        }
                        menuItems = response.Data.Select(mi => new MenuItemViewModel { Caption = mi.Title, Url = mi.Url }).ToList();
                    }
                    ViewBag.MenuString = sb.ToString();
                }
            }

            return View();
        }



        public ActionResult ChangeCulture(string lang, string returnUrl)
        {
            Session["Culture"] = new CultureInfo(lang);
            using (var api = ApiFactory.Create())
            {
                var request = new GetPageTranslationsRequest { PageUrl = returnUrl };

                var xx = api.Pages.Page.Translations.Get(request);
                if (xx.Data.TotalCount > 1)
                {

                    List<PageTranslationModel> pages1 = xx.Data.Items.ToList();
                    foreach (var item in pages1)
                    {
                        string language = item.LanguageCode != null ? item.LanguageCode : "vi";
                        if (language == lang)
                        {
                            return Redirect(item.PageUrl);
                        }
                    }
                }
            }
            return Redirect(returnUrl);
        }

        public virtual ActionResult SubMenu(string parentUrl)
        {
            //var menuItems = new List<MenuItemViewModel>();

            //using (var api = ApiFactory.Create())
            //{
            //    var pageRequest = new PageExistsRequest { PageUrl = parentUrl };
            //    var pageResponse = api.Pages.Page.Exists(pageRequest);

            //    var sitemapId = GetSitemapId(api);
            //    if (sitemapId.HasValue)
            //    {
            //        var parentRequest = new GetSitemapNodesRequest();
            //        parentRequest.SitemapId = sitemapId.Value;
            //        parentRequest.Data.Take = 1;
            //        parentRequest.Data.Filter.Add("ParentId", null);

            //        var filter = new DataFilter(FilterConnector.Or);
            //        parentRequest.Data.Filter.Inner.Add(filter);
            //        filter.Add("Url", parentUrl);
            //        if (pageResponse.Data.Exists)
            //        {
            //            filter.Add("PageId", pageResponse.Data.PageId.Value);
            //        }
            //        parentRequest.Data.Order.Add("DisplayOrder");

            //        var parentResponse = api.Pages.Sitemap.Nodes.Get(parentRequest);
            //        if (parentResponse.Data.Items.Count == 1)
            //        {
            //            var request = new GetSitemapTreeRequest { SitemapId = sitemapId.Value };
            //            request.Data.NodeId = parentResponse.Data.Items[0].Id;
            //            var response = api.Pages.Sitemap.Tree.Get(request);
            //            if (response.Data.Count > 0)
            //            {
            //                menuItems = response.Data.Select(mi => new MenuItemViewModel { Caption = mi.Title, Url = mi.Url }).ToList();
            //                //menuItems.Insert(0, new MenuItemViewModel { Caption = "Main", Url = parentUrl });
            //            }
            //        }
            //    }
            //}

            //return View(menuItems);
            var menuItems = new List<MenuItemViewModel>();

            using (var api = ApiFactory.Create())
            {
                var sitemapId = GetSitemapId(api);
                if (sitemapId.HasValue)
                {
                    var request = new GetSitemapTreeRequest { SitemapId = sitemapId.Value, Data = new GetSitemapTreeModel { LanguageId = LanguageHelper.CurrentLanguageId } };

                    var response = api.Pages.Sitemap.Tree.Get(request);
                    System.Text.StringBuilder sb = new System.Text.StringBuilder();
                    if (response.Data.Count > 0)
                    {
                        foreach (var item in response.Data)
                        {
                            if (item.ChildrenNodes.Count > 0)
                            {
                                if (item.Url == parentUrl)
                                {
                                    sb.Append("<div id=\"VMENU709487940\" class=\"VMENU\">");
                                    sb.Append("    <ul class=\"VMENU_0 VMENU_0_709487940 reset\">");
                                    foreach (var item1 in item.ChildrenNodes)
                                    {
                                        sb.Append("       <li>");
                                        sb.Append("       <a href=\""+item1.Url+"\" class=\"" + (System.Web.HttpContext.Current.Request.Path == item1.Url ? "a_s" : null) + "\"><span class=\"" + (System.Web.HttpContext.Current.Request.Path == item1.Url ? "s" : null) + "\">" + item1.Title + "</span></a>");
                                        sb.Append("       </li>");
                                        sb.Append("         <li class=\"d\"></li>");
                                    }
                                    sb.Append("    </ul>");
                                    sb.Append("</div>");


                                }

                            }
                        }
                        menuItems = response.Data.Select(mi => new MenuItemViewModel { Caption = mi.Title, Url = mi.Url }).ToList();
                    }
                    ViewBag.MenuString2 = sb.ToString();
                }
            }

            return View();
        }

       
        private Guid? GetSitemapId(IApiFacade api)
        {
            var allSitemaps = api.Pages.Sitemap.Get(new GetSitemapsRequest());
            if (allSitemaps.Data.Items.Count > 0)
            {
                var sitemap = allSitemaps.Data.Items.FirstOrDefault(map => map.Id == defaultSitemapId) ?? allSitemaps.Data.Items.First();
                return sitemap.Id;
            }

            return null;
        }
    }
}

BetterCms.Demo.Web/Views/Shared/Layouts/Light/_BcmsLightLayout.cshtml
@using BetterCms.Demo.Web
@{ Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml"; }

<!DOCTYPE html>
<html>
<head>
    <title>Bcms Light Layout</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700' rel='stylesheet' type='text/css'>
    <link href="/Content/Styles/bcms.light.layout.css" rel="stylesheet" />
    <link href="/Content/Styles/bcms.light.content.css" rel="stylesheet" />
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/modernizr.js")"></script>
    <![endif]-->
</head>
<body>
    @Html.Raw(MvcApplication.Resetter.GetHtml())
    <div class="page">
        <header class="page-header">
            <div class="page-frame clearfix">
                <a href="/" class="logo">
                    <img src="/Content/images/logo.png" alt="BetterCMS" />
                </a>
                <nav class="page-navigation" id="site-nav">
                    @{ Html.RenderAction("Index", "SiteMap", new { area = "" }); }
                </nav>
            </div>
        </header>

        <div class="page-block">
            
            <div class="default-messages-container">
                <div class="error-user-message-container">
                    <ins class="icon-static"></ins>
                    <div class="error user-message">
                    </div>
                </div>
                <div class="success-user-message-container">
                    <ins class="icon-static"></ins>
                    <div class="success user-message">
                    </div>
                </div>
            </div>

            <div class="page-frame clearfix">                
                @RenderSection("MainContent", false)
                @RenderBody()
            </div>
        </div>

    </div>

    <footer class="page-footer">
        <div class="page-frame clearfix">
            <span class="copyright">&copy; @DateTime.Now.Year Better CMS</span>
        </div>
    </footer>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")"></script>
    <script src="@Url.Content("~/Scripts/validation.extenders.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.accordion.js")"></script>
    <script src="@Url.Content("~/Scripts/slides.min.jquery.js")"></script>
    <script src="@Url.Content("~/Scripts/messages.js")"></script>
    <script src="@Url.Content("~/Scripts/forms.js")"></script>

    @RenderSection("Scripts", false)
</body>
</html>

BetterCms.Demo.Web/Views/Shared/Layouts/Light/_BlogPostLayout.cshtml
@using BetterCms.Module.Blog.Helpers.Extensions
@using BetterCms.Module.Pages.Helpers.Extensions
@using BetterCms.Module.Root.Mvc.Helpers

@{
    Layout = "~/Views/Shared/Layouts/Light/_LightTwoColumnsLayout.cshtml";
}

@{
    var authorName = string.Empty;
    var author = Model.GetBlogPostAuthorModel();
    if (author != null)
    {
        authorName = author.Name;
    }

    IList<string> tags;
    DateTime? date;
    if (Model.IsBlogPost())
    {
        date = Model.GetBlogPostModel().ActivationDate;
        tags = Model.GetPageTagsList();
    }
    else
    {
        date = null;
        tags = new List<string>();
    }
}


@model BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel

@section CMSMainContent {
    <section class="blogpost-head">
        <h1>@Model.Title<a onclick=" history.go(-1) " class="back-link">< Back</a></h1>
        <span class="author">@authorName</span>
        @if (date.HasValue)
        {
            <time datetime="@date.Value.ToString("yyyy-MM-dd")">@date.Value.ToString("MMM d, yyyy")</time>
        }
        @if (tags != null && tags.Count > 0)
        {
            var blogListUrl = Model.GetOptionValue<string>("Blogs List Page URL");
            if (!string.IsNullOrEmpty(blogListUrl))
            {
                <span>
                    @foreach (var tag in tags)
                    {
                        <a href="@blogListUrl?tagName=@tag" class="single-tag">@tag</a>
                    }
                </span>
            }
        }
    </section>

    @RenderSection("CMSMainContent", false)
}

@section ColRight {
    @RenderSection("ColRight", false)
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}

BetterCms.Demo.Web/Views/Shared/Layouts/Light/_ContactsLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightOneColumnLayout.cshtml";
}

@section MainContent {
    <div class="contact-info clearfix">
        <div class="clearfix">
            <div class="contact-address">
                @RenderSection("Address", false)
            </div>

            <div class="contact-social">
                @RenderSection("Social", false)                
            </div>
        </div>

        <div class="contact-map">
            @RenderSection("Map", false)
        </div>
    </div>

    <div class="contact-form">
        @RenderSection("Form", false)
    </div>
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}

BetterCms.Demo.Web/Views/Shared/Layouts/Light/_GalleryLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightOneColumnLayout.cshtml";
}

@section HeadScripts {
    <link href="/Content/Styles/bcms.light.gallery.css" rel="stylesheet" />
    
    @RenderSection("HeadScripts", false)
}

@section MainContent {
    <div id="gallery-main-content" style="visibility: hidden;">
        @RenderSection("MainContent", false)
    </div>
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
    @Html.Partial("Layouts/Light/Partial/_GalleryScripts")
    <script src="@Url.Content("~/Scripts/gallery.gallery.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.lightbox_me.js")"></script>
}

BetterCms.Demo.Web/Views/Shared/Layouts/Light/_HomeLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightOneColumnLayout.cshtml";
}

@section MainContent {
    <section class="home-banner" id="home-slides">
        @RenderSection("Slider", false)
    </section>
    
    <div class="home-bottom">
        <article>
            @RenderSection("Article", false)
        </article>
        
        <section class="home-gallery">
            <div id="gallery-main-content" style="visibility: hidden;">
                @RenderSection("SideBar", false)
            </div>
        </section>
    </div>
}

@section HeadScripts {
     <link href="/Content/Styles/bcms.light.gallery.css" rel="stylesheet" />
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
    @Html.Partial("Layouts/Light/Partial/_GalleryScripts")
    <script src="@Url.Content("~/Scripts/gallery.home.js")"></script>
}

BetterCms.Demo.Web/Views/Shared/Layouts/Light/_LightLayout.cshtml
@using BetterCms.Demo.Web

@{ Layout = "~/Areas/bcms-Root/Views/Shared/BaseLayout.cshtml"; }


@section HeadScripts {
    <meta charset="utf-8" />
    <link href="/Content/Styles/bcms.light.layout.css" rel="stylesheet" />
    <link href="/Content/Styles/bcms.light.content.css" rel="stylesheet" />
    <!--[if lt IE 9]>
        <script src="@Url.Content("~/Scripts/modernizr.js")"></script>
    <![endif]-->

    @RenderSection("HeadScripts", false)
}

@section Scripts {
    <script src="//codeorigin.jquery.com/jquery-1.8.3.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")"></script>
    <script src="@Url.Content("~/Scripts/validation.extenders.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.accordion.js")"></script>
    <script src="@Url.Content("~/Scripts/slides.min.jquery.js")"></script>
    <script src="@Url.Content("~/Scripts/messages.js")"></script>
    <script src="@Url.Content("~/Scripts/forms.js")"></script>

    @RenderSection("Scripts", false)
}

<div class="page">
    <header class="page-header">
        <div class="page-frame clearfix">
            <a href="/" class="logo">
                <img src="/Content/images/logo.png" alt="BetterCMS" />
            </a>
            <nav class="page-navigation" id="site-nav">
                @{ Html.RenderAction("Index", "SiteMap", new { area = "" }); }
            </nav>
            <div>
                @Html.ActionLink("Tieng Viet", "ChangeCulture", "Sitemap", new { lang = "vi", returnUrl = this.Request.RawUrl, area = "" }, null)
                @Html.ActionLink("English", "ChangeCulture", "Sitemap", new { lang = "en", returnUrl = this.Request.RawUrl, area = "" }, null)
            </div>
        </div>
    </header>

    <div class="page-block">

        <div class="default-messages-container">
            <div class="error-user-message-container">
                <ins class="icon-static"></ins>
                <div class="error user-message">
                </div>
            </div>
            <div class="success-user-message-container">
                <ins class="icon-static"></ins>
                <div class="success user-message">
                </div>
            </div>
        </div>

        <div class="page-frame clearfix">
            @RenderSection("MainContent", false)
            @RenderBody()
        </div>
    </div>

</div>

<footer class="page-footer">
    <div class="page-frame clearfix">
        <span class="copyright">&copy; @DateTime.Now.Year Better CMS</span>
    </div>
</footer>

BetterCms.Demo.Web/Views/Shared/Layouts/Light/_LightOneColumnLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightLayout.cshtml";
}

@section HeadScripts {
    @RenderSection("HeadScripts", false)
}


@section MainContent {
    @RenderSection("MainContent", false)
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}

BetterCms.Demo.Web/Views/Shared/Layouts/Light/_LightThreeColumnsLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightLayout.cshtml";
}

@section MainContent {
    <section class="three-col-left">
        @RenderSection("MainContent", false)
    </section>
    
    <section class="three-col-middle">
        @RenderSection("ColMiddle")
    </section>
    
    <aside class="col-right">
        @RenderSection("ColRight", false)
    </aside>
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}

BetterCms.Demo.Web/Views/Shared/Layouts/Light/_LightTwoColumnsLayout.cshtml
@{
    Layout = "~/Views/Shared/Layouts/Light/_LightLayout.cshtml";
}

@section MainContent {
    <section class="two-col-left">
        @RenderSection("CMSMainContent", false)
    </section>
    
    <aside class="col-right">
        @RenderSection("ColRight", false)
    </aside>
}

@RenderBody()

@section Scripts {
    @RenderSection("Scripts", false)
}